force-app/main/default/objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <label>Tag</label>
    <nameField>
        <label>Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tag_Relationship__c/Tag_Relationship__c.object-meta.xml
<CustomObject>
    <label>Tag Relationship</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Tag Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tag Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tag_Relationship__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>75</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tag_Relationship__c/fields/Record_Link__c.field-meta.xml
<CustomField>
    <fullName>Record_Link__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Record__c ,  Record_Name__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tag_Relationship__c/fields/Record_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Name__c</fullName>
    <label>Record Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tag_Relationship__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>Tag</label>
    <referenceTo>Tag__c</referenceTo>
    <relationshipLabel>Tag Relationships</relationshipLabel>
    <relationshipName>Tag_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tag_Relationship__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <formula>&apos;/&apos;&amp;  Record__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FindMatchingTagRelationships.cls
public with sharing class FindMatchingTagRelationships {
    @AuraEnabled
    public static List<Map<String, String>> findMatchingRelationships(String tagId) {
        system.Debug(tagId);
        List<Tag_Relationship__c> matchingRelationships = [SELECT Id, URL__c, Record_Name__c, Record_Link__c, Object_Name__c FROM Tag_Relationship__c WHERE Tag__c = :tagId];
        List<Map<String, String>> records = new List<Map<String, String>>();
        for(Tag_Relationship__c relationship : matchingRelationships) {
            Map<String, String> data = new Map<String, String>();
            data.put('id', relationship.Id);
            data.put('recordLink', relationship.URL__c);
            data.put('objectName', relationship.Object_Name__c);
            data.put('urlLabel', relationship.Record_Name__c);
            records.add(data);
            system.Debug(json.serialize(records));
        }
        return records;
    }
}