force-app/main/default/objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <label>Tag</label>
    <nameField>
        <label>Tag</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tag__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <defaultValue>&quot;tag&quot;</defaultValue>
    <label>Category</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tag__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <defaultValue>&quot;success&quot;</defaultValue>
    <label>Color</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>brightgreen</fullName>
            </value>
            <value>
                <fullName>green</fullName>
            </value>
            <value>
                <fullName>yellowgreen</fullName>
            </value>
            <value>
                <fullName>yellow</fullName>
            </value>
            <value>
                <fullName>orange</fullName>
            </value>
            <value>
                <fullName>red</fullName>
            </value>
            <value>
                <fullName>blue</fullName>
            </value>
            <value>
                <fullName>lightgrey</fullName>
            </value>
            <value>
                <fullName>success</fullName>
            </value>
            <value>
                <fullName>important</fullName>
            </value>
            <value>
                <fullName>critical</fullName>
            </value>
            <value>
                <fullName>informational</fullName>
            </value>
            <value>
                <fullName>inactive</fullName>
            </value>
            <value>
                <fullName>blueviolet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tag_Relationship__c/Tag_Relationship__c.object-meta.xml
<CustomObject>
    <label>Tag Relationship</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Tag Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tag Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tag_Relationship__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>Tag__r.Category__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tag_Relationship__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <formula>TEXT( Tag__r.Color__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Color</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tag_Relationship__c/fields/Record__c.field-meta.xml
<CustomField>
    <fullName>Record__c</fullName>
    <label>Record</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tag_Relationship__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>Tag</label>
    <referenceTo>Tag__c</referenceTo>
    <relationshipLabel>Tag Relationships</relationshipLabel>
    <relationshipName>Tag_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tag_Relationship__c/fields/Tag_Name__c.field-meta.xml
<CustomField>
    <fullName>Tag_Name__c</fullName>
    <formula>Tag__r.Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tag Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TagRelationshipSerializer.cls
public with sharing class TagRelationshipSerializer {
    @AuraEnabled(cacheable=true)
    public static List<Map<String, String>> getTagRelationships(Id recordId) {
        List<Map<String, String>> tagRelationships = new List<Map<String, String>>();
        for (Tag_Relationship__c tr : [SELECT Id, Category__c, Tag_Name__c, Color__c, Tag__c FROM Tag_Relationship__c WHERE Record__c = :recordId LIMIT 6]) {
            Map<String, String> trMap = new Map<String, String>();
            trMap.put('Category', tr.Category__c);
            trMap.put('Tag', tr.Tag_Name__c);
            trMap.put('Color', tr.Color__c);
            trMap.put('Id', tr.Tag__c);
            tagRelationships.add(trMap);
        }
        return tagRelationships;
    }

    @AuraEnabled(cacheable=true)
    public static List<Map<String, String>> getAllTagRelationships(Id recordId) {
        List<Map<String, String>> tagRelationships = new List<Map<String, String>>();
        for (Tag_Relationship__c tr : [SELECT Id, Category__c, Tag_Name__c, Color__c, Tag__c FROM Tag_Relationship__c WHERE Record__c = :recordId LIMIT 6]) {
            Map<String, String> trMap = new Map<String, String>();
            trMap.put('Category', tr.Category__c);
            trMap.put('Tag', tr.Tag_Name__c);
            trMap.put('Color', tr.Color__c);
            trMap.put('Id', tr.Tag__c);
            tagRelationships.add(trMap);
        }
        return tagRelationships;
    }
}