force-app/main/default/objects/Tags_Custom_Names__mdt/Tags_Custom_Names__mdt.object-meta.xml
<CustomObject>
    <label>Tags Custom Name</label>
    <pluralLabel>Tags Custom Names</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tags_Custom_Names__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tags_Custom_Names__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/QueryNameAction.cls
/**
 * @description       : 
 * @author            : Marc Swan
 * @group             : 
 * @last modified on  : 01-06-2023
 * @last modified by  : Marc Swan
 * Modifications Log
 * Ver   Date         Author      Modification
 * 1.0   01-06-2023   Marc Swan   Initial Version
**/
public class QueryNameAction {

    @AuraEnabled
    public static String runQuery(Id recordId, String objectName) {
    
    String output = '';
    
    Tags_Custom_Names__mdt customName = [SELECT Id, Field_API_Name__c FROM Tags_Custom_Names__mdt WHERE Object_API_Name__c = :objectName];
    if(customName != null) {
    output = [SELECT customName.Field_API_Name__c FROM objectType WHERE Id = :recordId].Field_API_Name__c;
    } else {
    output = [SELECT Name FROM objectType WHERE Id = :recordId].Name;
    }
    
    return output;
    
    }
    
    }